
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: b879645050817!
    driver-class-name: com.mysql.cj.jdbc.Driver

socket:
  port: 8000
  secretKey: VF2t@t>F};(U';I;MZB9Zg{w'2KY?p

server:
  port: 8003

